# Generated by Django 5.2.7 on 2025-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'History'},
        ),
        migrations.AddField(
            model_name='history',
            name='material_type',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('non-recycle', 'Non-Recyclable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='points',
            field=models.IntegerField(),
        ),
    ]
